server:
  port: 7002

eureka:
  instance:
    hostname: eureka7002.com
  client:
    register-with-eureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/